### ISSUE TITLE
Unable to cast object of type 'System.Linq.Expressions.FieldExpression' to type 'System.Linq.Expressions.ConstantExpression'

### ISSUE THREAD

**Issue by zhujinhu21** [SkyChenSky/Sikiro.Nosql.Mongo#12]
`      int addAge = 3;
            mongoRepository.Update<User>(a => a.Id == u.Id, a => new User
            {
                Sex = Sex.Woman,
                Age = a.Age + addAge
            });`
代码在调用var value = ((ConstantExpression)node.Right).Value; 转换报错:“Unable to cast object of type 'System.Linq.Expressions.FieldExpression' to type 'System.Linq.Expressions.ConstantExpression'.”

**Comment by SkyChenSky** [comment]
是因为自增age导致的异常吗？有没有用github的上源码尝试过。nuget上貌似不是最新的

**Comment by zhujinhu21** [comment]
使用的源码测试的，mongoRepository.Update<User>(a => a.Id == u.Id, a => new User { Sex = Sex.Woman, Age = a.Age + 1 });这样可以，但是Age = a.Age + addAge 就报错

**Comment by SkyChenSky** [comment]
好，我稍后看看

**Comment by zhujinhu21** [comment]
![微信截图_20191016133755](https://user-images.githubusercontent.com/4327149/66890902-3590aa80-f01a-11e9-84e4-3e6057038407.png)
谢谢

**Comment by SkyChenSky** [comment]
我已经签入了公司的生产版本，并且在Nuget发布了一个1.2.0版本，解决了这个问题，同时对部分方法做了修改。额外添加了两个内嵌数组的操作
