### ISSUE TITLE
给作者四点改进建议

### ISSUE THREAD

**Issue by AtlantisDe** [SkyChenSky/Sikiro.Nosql.Mongo#13]
### Description
首先非常感谢作者开源!谢谢.
使用过程发现可以给作者的四点建议.
目前最大的冲突就是在于实体类特性上,作者目前写法我目前认为是不太合理(不知道说得对不)
然后看下我给的建议!

### Now
- 现在使用过程感觉到这么设计使用起来不方便 我直接写成一张图片.
![avatar](https://img-bbs.csdn.net/upload/202008/18/1597751221_681415.png)
```C#
1. 仓库分离  

//准确讲是 实体特性与数据库和集合分离
var mongoRepository1 = new MongoRepository("mongodb://127.0.0.1:27017/ChengongTest1");
var mongoRepository2 = new MongoRepository("mongodb://127.0.0.1:27017/ChengongTest2");


**不要有数据库名称 和 集合名称特性 目前你这么设计 代码 入侵太过于严重 目前直接写死了 **
操作不同数据库的 集合就显得非常繁琐  (图片上有错别字)

一般都不是一个连接操作整个MongoDB的 而是分库操作

2.共用 实体类  需要取消数据库名称和集合名称,这个可以提前在
new mongoRepository 时候配置 collections 
我认为这样设计是合理的.同时解决缓存层问题 比如这样设计.
 
这个仓库用到的实体类对应的 collection 一次性写好写进去 
(至于怎么设计 我就暂时没想到了 作者可以思考.)  大概意思是

var mongoRepository1 = new MongoRepository("mongodb://127.0.0.1:27017/ChengongTest1");

// 准确的讲 这里应该是 配置实体对应的集合 
mongoRepository1 .Collectiona.Add(EntityUser,"UserTable")
mongoRepository1 .Collectiona.Add(EntityPass,"PassTable")
mongoRepository1 .Collectiona.Add(EntityOther,"OtherTable")


或者一个方法里面配置好每次需要用到直接这样写 反正灵活..
操作的时候反射出这个集合看你这么设计 就行 这样解决了 实体类共用的冲突 
 
```

### The  Last Extension
- MongoRepository.cs 这里面的方法 全部写成 [静态类扩展.]
- 最重要的扩展性方法静态化建议
- 最后一点建议: 希望你这些方法直接做成静态扩展 当别人用其它类库
- 比如下面代码支持其他类库操作的时候灵活扩展...使用
```C#
        /// <summary>
        /// 查
        /// </summary>
        /// <param name="predicate">条件</param>
        /// <param name="sort">排序字段</param>
        /// <returns></returns>
        public static T Get<T>(this IMongoCollection<T> coll, Expression<Func<T, bool>> predicate, Func<Sort<T>, Sort<T>> sort)
        {


            var find = coll.Find(predicate);

            if (sort != null)
                find = find.Sort(sort.GetSortDefinition());

            return find.FirstOrDefault();
        }


//使用的时候就这样..比如这样

var client = new MongoClient("mongodb://127.0.0.1:27017");
var database = client.GetDatabase("BigWenzhangData");

 var collection = database.GetCollection<User>("T_UsersDemo");
collection.Get () //这里直接集合类支持扩展了...非常方便 你写得方法都是通用的.

```

### pls help me 
 
```html
tks very much
```
### 期待改进版的到来.

**Comment by SkyChenSky** [comment]
首先非常感谢你认真的思考与建议的提交。那么针对你的问题我逐个解答

1.这是一个大前提，这个是一个mongodb的驱动的封装，并不是一个扩展，而我设计它的目的是减少开发人员对于原生驱动的API认知负担。原本写几句重复才能完成的功能，只需要我一个封装方法就好了。

2.仓库分离，在我设计初期，并没有考虑到多个不同MongoRepository的使用，因为在我的理解上，自带集群分片的功能，不需要多个不同的mongodb数据库连接。

3.你说的attribute入侵性，我不知道你为什么会纠结它，因为他是内存对象与数据库集合的映射关系，它们的映射关系不应该出现业务逻辑代码里例如你所描述的GetDatabase、GetCollection，这两个方法如果重复出现在逻辑代码里我认为是没有任何意义的。
那么只是在建立实体的时候打上一个标签作为映射关系，所以我不知道你为什么认为这个是一个非常严重侵入性的问题。换个角度问，打上这个标签会给你的整体的系统、框架、架构会带来哪一点的副作用？
一般我们说侵入性，主要是对已有业务逻辑、已经使用的框架造成了逻辑上的被修改或者使用的冲突，甚至是使用便捷和可读性

4.这个库已经在我呆过的两个的公司的生产环境使用了，很多的设计出自我呆的团队的需求出发，框架设计的初衷就是为了方便、快捷，低成本上手，如果你是为了灵活性，我建议用原生的没有封装不是更加灵活吗？

5.使用一个框架或者工具，应该优先了解它可以带来什么样的功能和它的设计思想是什么，还有目的。
您提的建议完全跟我的是一个另外思想的框架，因为我的是MIT协议的，如果我的框架里部分代码对您有用您可以借鉴去是实现一个属于你的Mongodb库

**Comment by AtlantisDe** [comment]
### 其实你目前的这样也可以 只不过我操作的时候需要带上数据库和集合名称 (代码侵入性表达有误)
```c#

//只不过我操作的时候需要带上数据库和集合名称
//"ChengongTest9", "User3"

            mongoRepository.Add("ChengongTest9", "User3", new UserNoDB
            {
                Name = "skychen",
                BirthDateTime = new DateTime(1991, 2, 2),
                AddressList = new List<string> { "guangdong", "guangzhou" },
                Sex = Sex.Woman,
                Son = new User
                {
                    Name = "xiaochenpi",
                    BirthDateTime = DateTime.Now
                }
            });

可能我想达到效果就是
var mongoRepository1 = new MongoRepository("mongodb://127.0.0.1:27017/ChengongTest1");
var mongoRepository2 = new MongoRepository("mongodb://127.0.0.1:27017/ChengongTest2");

提前对表和集合和类进行预先的相互绑定避免每次都是这样一个
 mongoRepository.Add("ChengongTest9", "User3",
这样带字符串去操作.
可能有点难受吧这样!
其实痛点在这里

可能代码侵入性表达有误
因为我发现去掉 就不存在代码特性侵入性问题.是我的错.
 

        [Mongo("ChengongTest", "User3")]
        public class User : MongoEntity
        {}

跟 

public class User : MongoEntity
        {}
效果一样 所以以前我一直以为 必须那样写.所以我这理解存在误区.

```

- 代码侵入性表达有误

**Comment by SkyChenSky** [comment]
我理解你的意思，
1.多仓储那个可能暂时不会改
2.如果1不改的话，下面去了atrribute的就不好切换库操作了，这两点相辅相成的

要不你fork我的代码，自己实现一下，因为设计上暂时还没打算改。您的建议虽好，但是对于我的设计理念刚好冲突。
对于修改我可以给你点建议：
1.可以把MongoAttribute强制逻辑判断去了
2.添加MongoEntity的子类的反射使用到GetCollection
3.对于不同database需要继承MongoRepository后使用例如：
`
pulic class CustomerRepository:MongoRepository
{
}
`
`
pulic class CompanyRepository:MongoRepository
{
}
`
`
services.AddSingleton(new CustomerRepository("mongodblink"));
services.AddSingleton(new CompanyRepository("mongodblink"));
`

当然你这边有更好的实习方式也欢迎跟我沟通。

**Comment by SkyChenSky** [comment]
刚刚更新了一个版本，兼容不需要MongoAttribute。
也是做一个尝试，看看是否满足大众的使用情况。

**Comment by AtlantisDe** [comment]
OK
