### ISSUE TITLE
关于查询条件的问题

### ISSUE THREAD

**Issue by alexljk** [SkyChenSky/Sikiro.Nosql.Mongo#7]
在查询时往往会有多个条件，有时并不是必须的，怎么写？

**Comment by alexljk** [comment]
比如方法中传入3个参数 其中有2个参数 会根据调用的地方传入空值，这时候其实是不需要去检查这个条件的

**Comment by SkyChenSky** [comment]
你意思是像列表查询那种情况吗？有值才会作为条件查询？

**Comment by SkyChenSky** [comment]
如果是，那么就是表达式拼接问题，可以参考我这个链接的帮助类 
https://github.com/SkyChenSky/Sikiro.DapperLambdaExtension.MsSql/blob/master/Sikiro.DapperLambdaExtension.MsSql.Core/Helper/ExpressionBuilder.cs
如果不是可以复制一段代码或者截图作为说明

**Comment by alexljk** [comment]
就是我要找的，谢谢
